[buildPlans.iosevka-ikrima]
family          = "Iosevka Ikrima"
spacing         = "normal"
serifs          = "sans"
no-cv-ss        = true
no-ligation     = true
[buildPlans.iosevka-ikrima.variants.design]
asterisk        = 'penta-low'
underscore      = 'high'
at              = 'threefold'
zero            = 'slashed'
brace           = "straight"

[buildPlans.iosevka-pragmata-pro]
family          = "Iosevka PragmataPro"
spacing         = "normal"
serifs          = "sans"
no-cv-ss        = true
[buildPlans.iosevka-pragmata-pro.variants]
inherits        = "ss08"
[buildPlans.iosevka-pragmata-pro.variants.design]
capital-a       = "curly-serifless"
capital-d       = "more-rounded-serifless"
capital-g       = "toothless-rounded-serifless-hooked"
capital-i       = "short-serifed"
capital-j       = "serifless"
capital-k       = "curly-serifless"
capital-n       = "asymmetric"
capital-q       = "straight"
capital-r       = "curly"
capital-v       = "curly"
capital-w       = "curly"
capital-x       = "curly-serifless"
capital-y       = "curly-serifless"
a               = "double-storey-serifless"
d               = "toothed-serifless"
e               = "flat-crossbar"
f               = "serifless"
g               = "double-storey"
i               = "serifed"
k               = "curly-serifless"
l               = "serifed"
u               = "toothed"
v               = "curly"
w               = "curly"
x               = "curly-serifless"
y               = "curly"
eszet           = "longs-s-lig"
lower-lambda    = "curly"
cyrl-capital-ka = "curly-serifless"
cyrl-ka         = "curly-serifless"
cyrl-capital-ya = "curly"
cyrl-ya         = "curly"
zero            = "dotted-oval"
four            = "closed"
six             = "closed-contour"
seven           = "bend-serifless"
nine            = "closed-contour"
asterisk        = "penta-low"
underscore      = "low"
brace           = "straight"
number-sign     = "slanted"
ampersand       = "upper-open"
at              = "threefold"
dollar          = "open"
cent            = "open"
percent         = "dots"
[buildPlans.iosevka-pragmata-pro.variants.italic]
g               = "single-storey-serifless"
[buildPlans.iosevka-pragmata-pro.metric-override]
leading         = 1180 # Default line height times 1000
cap             = 720  # Cap height (as well as ascender)]
# width         = 520 (wrong; this is the outdated setting) # Character width. Increase this if you think that Iosevka is too narrow
