[buildPlans]
#========================================================================================================================
# | Cheatsheat         | Desc                                                | Weights                                                                    | Slopes                   | Widths                          |
# | ------------------ | --------------------------------------------------- | -------------------------------------------------------------------------- | ------------------------ | ------------------------------- |
# | Iosevka            | Monospace, Sans-Serif, Ligation Off                 | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Semi-Extended, Extended |
# | Iosevka Term       | Monospace, Sans-Serif, Ligation Off, Narrow Symbols | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Semi-Extended, Extended |
# | Iosevka Fixed      | Monospace, Sans-Serif, Ligation Off, Narrow Symbols | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Semi-Extended, Extended |
# | Iosevka Slab       | Monospace, Slab-Serif, Ligation On                  | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Semi-Extended, Extended |
# | Iosevka Term Slab  | Monospace, Slab-Serif, Ligation On,  Narrow Symbols | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Semi-Extended, Extended |
# | Iosevka Fixed Slab | Monospace, Slab-Serif, Ligation Off, Narrow Symbols | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Semi-Extended, Extended |
# | Iosevka Aile       | Quasi-Proportional, Sans-Serif (for Documents)      | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal                          |
# | Iosevka Etoile     | Quasi-Proportional, Slab-Serif (for Writing)        | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal                          |

#========================================================================================================================
# BuildPlan: edev, monospace, sans-serif
[buildPlans.iosevka-edev]
family             = "Iosevka Edev"
desc               = "Edev Sans-Serif"
spacing            = "normal"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true
no-ligation        = true

  [buildPlans.iosevka-edev.widths]
  [buildPlans.iosevka-edev.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-edev.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-edev.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

  [buildPlans.iosevka-edev.variants]
  [buildPlans.iosevka-edev.variants.design]
  capital-i        = "short-serifed"
  i                = "serifed"
  l                = "zshaped"
  # zero           = "slashed"
  zero             = "diamond-reverse-slashed-split"
  four             = "closed"
  six              = "closed-contour"
  seven            = "curly-serifless"
  nine             = "closed-contour"
  asterisk         = "penta-low"
  underscore       = "high"
  brace            = "straight"
  number-sign      = "slanted"
  at               = "threefold"
  percent          = "dots"
  # paren          = "large-contour"
  paren            = "flat-arc"
  long-s           = "bent-hook-middle-serifed"
  eszet            = "longs-s-lig-serifless"
  capital-delta    = "curly"
  lower-delta      = "flat-top"
  capital-lambda   = "curly-serifless"
  lower-lambda     = "curly"
  lower-mu         = "toothed-serifless"
  lower-chi        = "curly-serifless"
  cyrl-capital-zhe = "curly"
  cyrl-zhe         = "curly"
  cyrl-capital-ka  = "curly-serifless"
  cyrl-capital-u   = "curly-serifless"
  cyrl-ka          = "curly-serifless"
  cyrl-capital-ya  = "curly-serifless"
  cyrl-ya          = "curly-serifless"
  guillemet        = "straight"
  lig-ltgteq       = "slanted"
  lig-neq          = "slightly-slanted-dotted"
  lig-equal-chain  = "with-notch"
  lig-hyphen-chain = "with-notch"

  [buildPlans.iosevka-edev.variants.italic]
  g                = "single-storey-serifless"

  [buildPlans.iosevka-edev.variants.slab-override.design]
  seven            = "bend-serifed"
  long-s           = "bent-hook-double-serifed"
  eszet            = "longs-s-lig-bottom-serifed"
  capital-lambda   = "curly-base-serifed"
  lower-mu         = "toothed-serifed"
  lower-chi        = "curly-serifed"
  cyrl-capital-ka  = "curly-serifed"
  cyrl-capital-u   = "curly-serifed"
  cyrl-ka          = "curly-serifed"
  cyrl-capital-ya  = "curly-serifed"
  cyrl-ya          = "curly-serifed"

  [buildPlans.iosevka-edev.variants.slab-override.italic]
  g                = "single-storey-serifed"
  cyrl-ka          = "curly-top-left-serifed"


[buildPlans.iosevka-edev-term]
family             = "Iosevka Edev Term"
spacing            = "term"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true
no-ligation        = true

  [buildPlans.iosevka-edev-term.variants]
  inherits         = "buildPlans.iosevka-edev"

  [buildPlans.iosevka-edev-term.widths]
  [buildPlans.iosevka-edev-term.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-edev-term.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-edev-term.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

[buildPlans.iosevka-edev-fixed]
family             = "Iosevka Edev Fixed"
spacing            = "fixed"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true
no-ligation        = true

  [buildPlans.iosevka-edev-fixed.variants]
  inherits         = "buildPlans.iosevka-edev"

  [buildPlans.iosevka-edev-fixed.widths]
  [buildPlans.iosevka-edev-fixed.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-edev-fixed.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-edev-fixed.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"


#========================================================================================================================
# BuildPlan: edev, monospace, slab-serif
[buildPlans.iosevka-edev-slab]
family             = "Iosevka Edev Slab"
desc               = "Edev Slab-Serif"
spacing            = "normal"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-edev-slab.variants]
  inherits         = "buildPlans.iosevka-edev"

  [buildPlans.iosevka-edev-slab.widths]
  [buildPlans.iosevka-edev-slab.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-edev-slab.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-edev-slab.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"


[buildPlans.iosevka-edev-term-slab]
family             = "Iosevka Edev Term Slab"
spacing            = "term"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-edev-term-slab.variants]
  inherits         = "buildPlans.iosevka-edev"

  [buildPlans.iosevka-edev-term-slab.widths]
  [buildPlans.iosevka-edev-term-slab.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-edev-term-slab.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-edev-term-slab.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

[buildPlans.iosevka-edev-fixed-slab]
family             = "Iosevka Edev Fixed Slab"
spacing            = "fixed"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-edev-fixed-slab.variants]
  inherits         = "buildPlans.iosevka-edev"

  [buildPlans.iosevka-edev-fixed-slab.widths]
  [buildPlans.iosevka-edev-fixed-slab.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-edev-fixed-slab.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-edev-fixed-slab.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

#========================================================================================================================
# BuildPlan: pragpro, monospace, sans-serif
[buildPlans.iosevka-pragpro]
family             = "Iosevka Pragpro"
desc               = "PragmataPro Sans-Serif"
spacing            = "normal"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro.variants]
  inherits = "ss08"

  [buildPlans.iosevka-pragpro.variants.design]
  capital-a        = "curly-serifless"
  capital-d        = "more-rounded-serifless"
  capital-g        = "toothless-rounded-serifless-hooked"
  capital-i        = "short-serifed"
  capital-j        = "serifless"
  capital-k        = "curly-serifless"
  capital-n        = "asymmetric-serifless"
  capital-q        = "straight"
  capital-r        = "curly-serifless"
  capital-v        = "curly-serifless"
  capital-w        = "curly-serifless"
  capital-x        = "curly-serifless"
  capital-y        = "curly-serifless"
  capital-z        = "curly-serifless"
  a                = "double-storey-serifless"
  d                = "toothed-serifless"
  e                = "flat-crossbar"
  f                = "serifless"
  g                = "double-storey"
  i                = "serifed"
  k                = "curly-serifless"
  l                = "zshaped"
  u                = "toothed-serifless"
  v                = "curly-serifless"
  w                = "curly-serifless"
  x                = "curly-serifless"
  y                = "curly-serifless"
  z                = "curly-serifless"
  long-s           = "bent-hook-middle-serifed"
  eszet            = "longs-s-lig-serifless"
  capital-delta    = "curly"
  lower-delta      = "flat-top"
  capital-lambda   = "curly-serifless"
  lower-lambda     = "curly"
  lower-mu         = "toothed-serifless"
  lower-chi        = "curly-serifless"
  cyrl-capital-zhe = "curly"
  cyrl-zhe         = "curly"
  cyrl-capital-ka  = "curly-serifless"
  cyrl-capital-u   = "curly-serifless"
  cyrl-ka          = "curly-serifless"
  cyrl-capital-ya  = "curly-serifless"
  cyrl-ya          = "curly-serifless"
  zero             = "diamond-reverse-slashed-split"
  four             = "closed"
  six              = "closed-contour"
  seven            = "curly-serifless"
  nine             = "closed-contour"
  asterisk         = "penta-low"
  underscore       = "high"
  brace            = "straight"
  number-sign      = "slanted"
  ampersand        = "upper-open"
  at               = "threefold"
  dollar           = "open"
  cent             = "open"
  percent          = "dots"
  paren            = "large-contour"
  guillemet        = "straight"
  lig-ltgteq       = "slanted"
  lig-neq          = "slightly-slanted-dotted"
  lig-equal-chain  = "with-notch"
  lig-hyphen-chain = "with-notch"

  [buildPlans.iosevka-pragpro.variants.italic]
  g                = "single-storey-serifless"

  [buildPlans.iosevka-pragpro.variants.slab-override.design]
  capital-a        = "curly-base-serifed"
  capital-d        = "more-rounded-bilateral-serifed"
  capital-g        = "toothless-rounded-serifed-hooked"
  capital-j        = "serifed"
  capital-k        = "curly-serifed"
  capital-n        = "asymmetric-serifed"
  capital-r        = "curly-serifed"
  capital-v        = "curly-serifed"
  capital-w        = "curly-serifed"
  capital-x        = "curly-serifed"
  capital-y        = "curly-serifed"
  capital-z        = "curly-serifed"
  a                = "double-storey-serifed"
  d                = "toothed-serifed"
  f                = "serifed"
  k                = "curly-serifed"
  u                = "toothed-serifed"
  v                = "curly-serifed"
  w                = "curly-serifed"
  x                = "curly-serifed"
  y                = "curly-serifed"
  z                = "curly-serifed"
  long-s           = "bent-hook-double-serifed"
  eszet            = "longs-s-lig-bottom-serifed"
  capital-lambda   = "curly-base-serifed"
  lower-mu         = "toothed-serifed"
  lower-chi        = "curly-serifed"
  cyrl-capital-ka  = "curly-serifed"
  cyrl-capital-u   = "curly-serifed"
  cyrl-ka          = "curly-serifed"
  cyrl-capital-ya  = "curly-serifed"
  cyrl-ya          = "curly-serifed"
  seven            = "bend-serifed"

  [buildPlans.iosevka-pragpro.variants.slab-override.italic]
  g                = "single-storey-serifed"
  v                = "curly-motion-serifed"
  w                = "curly-motion-serifed"
  x                = "curly-motion-serifed"
  y                = "curly-motion-serifed"
  cyrl-ka          = "curly-top-left-serifed"

  [buildPlans.iosevka-pragpro.widths]
  [buildPlans.iosevka-pragpro.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-pragpro.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-pragpro.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

[buildPlans.iosevka-pragpro-term]
family             = "Iosevka Pragpro Term"
spacing            = "term"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-term.variants]
  inherits = "buildPlans.iosevka-pragpro"

  [buildPlans.iosevka-pragpro-term.widths]
  [buildPlans.iosevka-pragpro-term.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-pragpro-term.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-pragpro-term.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

[buildPlans.iosevka-pragpro-fixed]
family             = "Iosevka Pragpro Fixed"
spacing            = "fixed"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-fixed.variants]
  inherits = "buildPlans.iosevka-pragpro"

  [buildPlans.iosevka-pragpro-fixed.widths]
  [buildPlans.iosevka-pragpro-fixed.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-pragpro-fixed.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-pragpro-fixed.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

#========================================================================================================================
# BuildPlan: pragpro, monospace, slab-serif
[buildPlans.iosevka-pragpro-slab]
family             = "Iosevka Pragpro Slab"
desc               = "PragmataPro Slab-Serif"
spacing            = "normal"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-slab.variants]
  inherits = "buildPlans.iosevka-pragpro"

  [buildPlans.iosevka-pragpro-slab.widths]
  [buildPlans.iosevka-pragpro-slab.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-pragpro-slab.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-pragpro-slab.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

[buildPlans.iosevka-pragpro-term-slab]
family             = "Iosevka Pragpro Term Slab"
spacing            = "term"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-term-slab.variants]
  inherits = "buildPlans.iosevka-pragpro"

  [buildPlans.iosevka-pragpro-term-slab.widths]
  [buildPlans.iosevka-pragpro-term-slab.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-pragpro-term-slab.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-pragpro-term-slab.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

[buildPlans.iosevka-pragpro-fixed-slab]
family             = "Iosevka Pragpro Fixed Slab"
spacing            = "fixed"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-fixed-slab.variants]
  inherits = "buildPlans.iosevka-pragpro"

  [buildPlans.iosevka-pragpro-fixed-slab.widths]
  [buildPlans.iosevka-pragpro-fixed-slab.widths.normal]
  shape = 500
  menu  = 5
  css   = "normal"
  [buildPlans.iosevka-pragpro-fixed-slab.widths.semiextended]
  shape = 548
  menu  = 6
  css   = "semi-expanded"
  [buildPlans.iosevka-pragpro-fixed-slab.widths.extended]
  shape = 600
  menu  = 7
  css   = "expanded"

#========================================================================================================================
# Collect plans
[collectPlans.iosevka-edev]
from = [
  "iosevka-edev",
  "iosevka-edev-term",
  "iosevka-edev-fixed"
]
[collectPlans.iosevka-edev-slab]
from = [
  "iosevka-edev-slab",
  "iosevka-edev-term-slab",
  "iosevka-edev-fixed-slab"
]
[collectPlans.iosevka-pragpro]
from = [
  "iosevka-pragpro",
  "iosevka-pragpro-term",
  "iosevka-pragpro-fixed"
]
[collectPlans.iosevka-pragpro-slab]
from = [
  "iosevka-pragpro-slab",
  "iosevka-pragpro-term-slab",
  "iosevka-pragpro-fixed-slab"
]
