#========================================================================================================================
# | Cheatsheat         | Desc                                                | Weights                                                                    | Slopes                   | Widths           |
# | ------------------ | --------------------------------------------------- | -------------------------------------------------------------------------- | ------------------------ | ---------------- |
# | Iosevka            | Monospace, Sans-Serif                               | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Extended |
# | Iosevka Term       | Monospace, Sans-Serif, Narrow Symbols               | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Extended |
# | Iosevka Fixed      | Monospace, Sans-Serif, Narrow Symbols, Ligation Off | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Extended |
# | Iosevka Slab       | Monospace, Slab-Serif                               | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Extended |
# | Iosevka Term Slab  | Monospace, Slab-Serif, Narrow Symbols               | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Extended |
# | Iosevka Fixed Slab | Monospace, Slab-Serif, Narrow Symbols, Ligation Off | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | Normal, Extended |
# | Iosevka Aile       | Quasi-Proportional, for Documents                   | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | -                |
# | Iosevka Etoile     | Quasi-Proportional, for Writing                     | Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Heavy | Upright, Oblique, Italic | -                |

#========================================================================================================================
# BuildPlan: edev, monospace, sans-serif
[buildPlans.iosevka-edev]
family             = "Iosevka Edev"
desc               = "Edev Sans-Serif"
spacing            = "normal"
serifs             = "sans"
no-cv-ss           = true
export-glyph-names = true
no-ligation        = true
  [buildPlans.iosevka-edev.variants.design]
  zero       = "slashed"
  asterisk   = "penta-low"
  underscore = "high"
  brace      = "straight"
  at         = "threefold"

[buildPlans.iosevka-edev-term]
family             = "Iosevka Edev Term"
spacing            = "term"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true
no-ligation        = true
  [buildPlans.iosevka-edev-term.variants.design]
  zero       = "slashed"
  asterisk   = "penta-low"
  underscore = "high"
  brace      = "straight"
  at         = "threefold"

[buildPlans.iosevka-edev-fixed]
family             = "Iosevka Edev Fixed"
spacing            = "fixed"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true
no-ligation        = true
  [buildPlans.iosevka-edev-fixed.variants.design]
  zero       = "slashed"
  asterisk   = "penta-low"
  underscore = "high"
  brace      = "straight"
  at         = "threefold"

#========================================================================================================================
# BuildPlan: edev, monospace, slab-serif
[buildPlans.iosevka-edev-slab]
family             = "Iosevka Edev Slab"
desc               = "Edev Slab-Serif"
spacing            = "normal"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true
  [buildPlans.iosevka-edev-slab.variants.design]
  zero       = "slashed"
  asterisk   = "penta-low"
  underscore = "high"
  brace      = "straight"
  at         = "threefold"

[buildPlans.iosevka-edev-term-slab]
family             = "Iosevka Edev Term Slab"
spacing            = "term"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true
  [buildPlans.iosevka-edev-term-slab.variants.design]
  zero       = "slashed"
  asterisk   = "penta-low"
  underscore = "high"
  brace      = "straight"
  at         = "threefold"

[buildPlans.iosevka-edev-fixed-slab]
family             = "Iosevka Edev Fixed Slab"
spacing            = "fixed"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true
  [buildPlans.iosevka-edev-fixed-slab.variants.design]
  zero       = "slashed"
  asterisk   = "penta-low"
  underscore = "high"
  brace      = "straight"
  at         = "threefold"

#========================================================================================================================
# BuildPlan: pragpro, monospace, sans-serif
[buildPlans.iosevka-pragpro]
family             = "Iosevka Pragpro"
desc               = "PragmataPro Sans-Serif"
spacing            = "normal"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro.variants]
  inherits = "ss08"

    [buildPlans.iosevka-pragpro.variants.design]
    capital-a       = "curly-serifless"
    capital-d       = "more-rounded-serifless"
    capital-g       = "toothless-rounded-serifless-hooked"
    capital-i       = "short-serifed"
    capital-j       = "serifless"
    capital-k       = "curly-serifless"
    capital-n       = "asymmetric"
    capital-q       = "straight"
    capital-r       = "curly"
    capital-v       = "curly"
    capital-w       = "curly"
    capital-x       = "curly-serifless"
    capital-y       = "curly-serifless"
    a               = "double-storey-serifless"
    d               = "toothed-serifless"
    e               = "flat-crossbar"
    f               = "serifless"
    g               = "double-storey"
    i               = "serifed"
    k               = "curly-serifless"
    l               = "serifed"
    u               = "toothed"
    v               = "curly"
    w               = "curly"
    x               = "curly-serifless"
    y               = "curly"
    eszet           = "longs-s-lig"
    lower-lambda    = "curly"
    cyrl-capital-ka = "curly-serifless"
    cyrl-ka         = "curly-serifless"
    cyrl-capital-ya = "curly"
    cyrl-ya         = "curly"
    zero            = "dotted-oval"
    four            = "closed"
    six             = "closed-contour"
    seven           = "bend-serifless"
    nine            = "closed-contour"
    asterisk        = "penta-low"
    underscore      = "low"
    brace           = "straight"
    number-sign     = "slanted"
    ampersand       = "upper-open"
    at              = "threefold"
    dollar          = "open"
    cent            = "open"
    percent         = "dots"

    [buildPlans.iosevka-pragpro.variants.italic]
    g               = "single-storey-serifless"

[buildPlans.iosevka-pragpro-term]
family             = "Iosevka Pragpro Term"
spacing            = "term"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-term.variants]
  inherits = "buildPlans.iosevka-pragpro"

[buildPlans.iosevka-pragpro-fixed]
family             = "Iosevka Pragpro Fixed"
spacing            = "fixed"
serifs             = "sans"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-fixed.variants]
  inherits = "buildPlans.iosevka-pragpro"

#========================================================================================================================
# BuildPlan: pragpro, monospace, slab-serif
[buildPlans.iosevka-pragpro-slab]
family             = "Iosevka Pragpro Slab"
desc               = "PragmataPro Slab-Serif"
spacing            = "normal"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-slab.variants]
  inherits = "buildPlans.iosevka-pragpro"

[buildPlans.iosevka-pragpro-term-slab]
family             = "Iosevka Pragpro Term Slab"
spacing            = "term"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-term-slab.variants]
  inherits = "buildPlans.iosevka-pragpro"

[buildPlans.iosevka-pragpro-fixed-slab]
family             = "Iosevka Pragpro Fixed Slab"
spacing            = "fixed"
serifs             = "slab"
export-glyph-names = true
no-cv-ss           = true

  [buildPlans.iosevka-pragpro-fixed-slab.variants]
  inherits = "buildPlans.iosevka-pragpro"

#========================================================================================================================
# Collect plans
[collectPlans.iosevka-edev]
from = [
  "iosevka-edev",
  "iosevka-edev-term",
  "iosevka-edev-fixed"
]
[collectPlans.iosevka-edev-slab]
from = [
  "iosevka-edev-slab",
  "iosevka-edev-term-slab",
  "iosevka-edev-fixed-slab"
]
[collectPlans.iosevka-pragpro]
from = [
  "iosevka-pragpro",
  "iosevka-pragpro-term",
  "iosevka-pragpro-fixed"
]
[collectPlans.iosevka-pragpro-slab]
from = [
  "iosevka-pragpro-slab",
  "iosevka-pragpro-term-slab",
  "iosevka-pragpro-fixed-slab"
]